### ISSUE TITLE
 error when there is a special character

### ISSUE THREAD

**Issue by MrBn100ful** [alessioalex/get-folder-size#8] opened 2018-04-19 11:58 UTC
Hello, when i try to use your module. I get a error. I think it's becose my file name have special character.

root@SRV:~# node app.js
[ 'new' ]
/root/app.js:169
if (err) throw err
         ^

Error: ENOENT: no such file or directory, lstat '/ftp/user/document/Canap� v 01.png'

thanks

**Comment by alessioalex** [comment] 2018-04-27 07:44
Hey @MrBn100ful thanks for reporting this. Can you paste me the original filename so that I can try to reproduce this locally? thanks

**Comment by MikPak** [comment] 2019-03-01 21:13
Can confirm this error:

`Error: ENOENT: no such file or directory, lstat '/var/public_html/asiakas/xxx/data/xmll�t'`

**Comment by alessioalex** [comment] 2019-03-04 08:03
Thanks @MikPak will take another look at this.

**Comment by ph1823** [comment] 2020-09-20 12:55
Me too i can confirm, error:
```
erreur: sizeError: ENOENT: no such file or directory, lstat '/home/datahosting/new-minecraft/30/yo �a va'
```
File name: "yo ça va", i check with space and no "ç" char and that work, the bug happens only with certain character. No solve is planned?

**Comment by alessioalex** [comment] 2020-09-20 15:25
Hi @ph1823 the problem is that I just cannot replicate this. I copy paste for example the filename to "yo ça va.txt" and it works properly no error when running the example. I've tried this on Ubuntu initially as well as Windows now.

**Comment by ph1823** [comment] 2020-09-20 15:37
ah thin .. here is some more information to help you:
I am use debian 10 with node v10.

I dont try if work on windows or ubuntu but on debian 10 ans with node v10 doest work :/

**Comment by Devhercule** [comment] 2020-12-18 17:26
I confirm this issue. I have the same error when trying to get a chrome profile dir size: 

`error: profile dir size error :  ENOENT: no such file or directory, lstat '/home/.../profile-dir-885ef0ca-b528-4684-be84-80168b6b6487/Default/Cache/todelete_dae30b18c8893bda_0_1' {"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/home/.../profile-dir-885ef0ca-b528-4684-be84-80168b6b6487/Default/Cache/todelete_dae30b18c8893bda_0_1","stack":"Error: ENOENT: no such file or directory, lstat '/home/.../profile-dir-885ef0ca-b528-4684-be84-80168b6b6487/Default/Cache/todelete_dae30b18c8893bda_0_1'"}`

**Comment by atjn** [comment] 2021-05-06 08:30
Can any of you provide a full step-by-step guide to reproduce this error? It seems impossible that this issue could be part of get-folder-size.

I would like you to tell me exactly what folder structure to make, and exactly what command you used / what code you ran to get this error.

**Comment by atjn** [comment] 2021-05-20 16:08
I'm closing this for now. Feel free to reopen it if you can document how to reproduce the error :)

**Closed by atjn** 2021-05-20 16:08 UTC
